from .fetcher import fetch_html, fetch_all_pages_ki
from .parser import (
    parse_jobs_lund,
    parse_jobs_uppsala,
    parse_jobs_stockholm,
    parse_jobs_gothenburg,
    parse_jobs_ki,
    parse_jobs_kth,
    parse_jobs_linkoping,
    parse_jobs_umea,
    parse_jobs_orebro,
    parse_jobs_lulea,
    parse_jobs_malmo,
    parse_jobs_chalmers,
    parse_jobs_slu,
    parse_jobs_karlstad,
    parse_jobs_sodertorn,
    parse_jobs_dalarna,
    parse_jobs_gavle,
    parse_jobs_malardalen,
    parse_jobs_miun,
)

UNIVERSITIES = [
    {
        "slug": "lund",
        "name": "Lund University",
        "url": "https://www.lunduniversity.lu.se/vacancies",
        "fetcher": fetch_html,
        "parser": parse_jobs_lund,
    },
    {
        "slug": "uppsala",
        "name": "Uppsala University",
        "url": "https://www.uu.se/en/about-uu/join-us/jobs-and-vacancies?start=200",
        "fetcher": fetch_html,
        "parser": parse_jobs_uppsala,
    },
    {
        "slug": "stockholm",
        "name": "Stockholm University",
        "url": "https://su.varbi.com/en/what:findjob/?showresult=1&categories=1&checklist=1&orglevel=1&ref=1&nologin=1&nocity=1&nocounty=1&nocountry=1&nolocalefield=1&nolocalegroup=1&hideColumns=town&norefsearch=1",
        "fetcher": fetch_html,
        "parser": parse_jobs_stockholm,
    },
    {
        "slug": "gothenburg",
        "name": "Gothenburg University",
        "url": "https://www.gu.se/en/work-at-the-university-of-gothenburg/vacancies",
        "fetcher": fetch_html,
        "parser": parse_jobs_gothenburg,
    },
    {
        "slug": "ki",
        "name": "Karolinska Institute",
        "url": "https://ki.se/en/vacancies?page=",
        "fetcher": fetch_all_pages_ki,
        "parser": parse_jobs_ki,
    },
    {
        "slug": "kth",
        "name": "KTH",
        "url": "https://www.kth.se/lediga-jobb?l=en",
        "fetcher": fetch_html,
        "parser": parse_jobs_kth,
    },
    {
        "slug": "linkoping",
        "name": "Linköping University",
        "url": "https://liu.se/en/work-at-liu/vacancies",
        "fetcher": fetch_html,
        "parser": parse_jobs_linkoping,
    },
    {
        "slug": "umea",
        "name": "Umeå University",
        "url": "https://www.umu.se/en/work-with-us/open-positions/",
        "fetcher": fetch_html,
        "parser": parse_jobs_umea,
    },
    {
        "slug": "orebro",
        "name": "Örebro University",
        "url": "https://www.oru.se/english/career/available-positions",
        "fetcher": fetch_html,
        "parser": parse_jobs_orebro,
    },
    {
        "slug": "lulea",
        "name": "Luleå University",
        "url": "https://www.ltu.se/en/about-the-university/work-with-us/job-vacancies",
        "fetcher": fetch_html,
        "parser": parse_jobs_lulea,
    },
    {
        "slug": "malmo",
        "name": "Malmö University",
        "url": "https://mau.se/en/about-us/job-offers/current-vacancies/",
        "fetcher": fetch_html,
        "parser": parse_jobs_malmo,
    },
    {
        "slug": "chalmers",
        "name": "Chalmers University of Technology",
        "url": "https://web103.reachmee.com/ext/I003/304/main?site=5&validator=a72aeedd63ec10de71e46f8d91d0d57c&lang=UK&ref=https%3A%2F%2F",
        "fetcher": fetch_html,
        "parser": parse_jobs_chalmers,
    },
    {
        "slug": "slu",
        "name": "Swedish University of Agricultural Sciences",
        "url": "https://web103.reachmee.com/ext/I017/1114/main?site=7&validator=87e4b706891e51f731ed44be28da8352&lang=UK&ref=https%3a%2f%2fwww.overleaf.com%2f",
        "fetcher": fetch_html,
        "parser": parse_jobs_slu,
    },
    {
        "slug": "karlstad",
        "name": "Karlstad University",
        "url": "https://kau.varbi.com/en/what:iframe/login:1/buttons:1/subscribe:1/template:default",
        "fetcher": fetch_html,
        "parser": parse_jobs_karlstad,
    },
    {
        "slug": "sodertorn",
        "name": "Södertörn University",
        "url": "https://web103.reachmee.com/ext/I007/532/main?site=24&validator=2f5f4343b7f80edb4b210427ef968f34&lang=UK&ref=https%3a%2f%2fwww.overleaf.com%2f",
        "fetcher": fetch_html,
        "parser": parse_jobs_sodertorn,
    },
    {
        "slug": "dalarna",
        "name": "Dalarna University",
        "url": "https://www.du.se/en/about-du/career-opportunities/vacant-positions/",
        "fetcher": fetch_html,
        "parser": parse_jobs_dalarna,
    },
    {
        "slug": "gavle",
        "name": "Gävle University",
        "url": "https://www.hig.se/engelska/university-of-gavle/about-the-university/work-with-us#Currentvacancies",
        "fetcher": fetch_html,
        "parser": parse_jobs_gavle,
    },
    {
        "slug": "malardalen",
        "name": "Mälardalen University",
        "url": "https://www.mdu.se/en/malardalen-university/about-mdu/work-with-us/job-opportunities",
        "fetcher": fetch_html,
        "parser": parse_jobs_malardalen,
    },
    {
        "slug": "miun",
        "name": "Mid Sweden University",
        "url": "https://www.miun.se/en/work-at-the-university/career/",
        "fetcher": fetch_html,
        "parser": parse_jobs_miun,
    },    
]
